### ISSUE TITLE
How to get Enterprise version of Insider Dev build 22567?

### ISSUE THREAD

**Issue by D4rkov** [gus33000/UUPMediaCreator#100]
Hello, I kinda wanna get Enterprise edition of build 22567, anyone know the right commands to get that?
Or should I just get professional and then just change my product key later on after it's installed?
Cause what UUPDump shows me, that for Enterprise I need pro edition.
Apologies for the white mode, I haven't set my computer to dark mode cause I be reinstalling a lot.
![image](https://user-images.githubusercontent.com/83168801/156876659-1bd8d98d-8b6e-4093-aca6-fbdfa96c5fae.png)

**Comment by D4rkov** [comment]
Like this?

-s Enterprise -v 10.0.22567.1 -r External -b Dev -c ni_release -t amd64 -e Enterprise -l en-US

**Comment by gus33000** [comment]
The parameters you use for uupdownload are for reporting what edition you are currently running. Enterprise is what is called a "Virtual edition". It builds on top of pro. So you need to download Pro first, like so:

`uupdownload -s Enterprise -v 10.0.22567.1 -r External -b Dev -c ni_release -t amd64 -e Professional -l en-US`

and then you run the conversion tool, **without** specifying a target edition, as administrator, like so:

`uupmediaconverter -u "C:\Users\Darkov\Desktop\CLI\10.0.22567.100.ni_release_svc_prod1.220225-1517_amd64fre_4658f0069f51" -i "C:\Users\Darkov\Desktop\Windows11.iso" -l en-US`

**Comment by gus33000** [comment]
On that subject, a bit off topic to this issue, but thought like mentioning it, I see you're using uupdownload parameters to pinpoint what you want to grab, but that's not quite what these parameters do.

`-s Enterprise -v 10.0.22567.1 -r External -b Dev -c ni_release -t amd64`

this set of parameters serves a single purpose, telling Windows Update, hey, I currently run this, what can you offer me at the moment?

You got lucky here that it worked, but if you want the best chance of getting an update (it's an update client after all) you should report that you're running an **older build** than the one you are currently running, like so:

`uupdownload -s Enterprise -v 10.0.22563.1 -r External -b Dev -c ni_release -t amd64 -e Professional -l en-US`

This will __still give you 22567__ exactly because these parameters, do not tell WU, I want to get this, but rather tell WU, I currently run this. If you want to get exactly one older build, you would use something like the `-y` option. (More details in help)

**Comment by gus33000** [comment]
I'm going to mark this as closed due to an answer being given, if there's still further issues I will reopen the issue.

**Comment by akuropka** [comment]
@gus33000, thank you for your detailed explanation in https://github.com/gus33000/UUPMediaCreator/issues/100#issuecomment-1059834010. Yet I am wondering why for example `uupdownload -s Professional -v 10.0.22567.100 -r External -b Dev -c ni_release -t amd64 -e Professional -l de-DE` finds and downloads updates. Maybe you can help me out for better understanding... thank you in advance!

**Comment by gus33000** [comment]
> @gus33000, thank you for your detailed explanation in [#100 (comment)](https://github.com/gus33000/UUPMediaCreator/issues/100#issuecomment-1059834010). Yet I am wondering why for example `uupdownload -s Professional -v 10.0.22567.100 -r External -b Dev -c ni_release -t amd64 -e Professional -l de-DE` finds and downloads updates. Maybe you can help me out for better understanding... thank you in advance!

With insider builds MS added the ability for the OS to get a new copy of the Windows Recovery Environment using Windows Update, so they make the update show up even if you currently run that Windows version so the OS can pick this up for fixing WinRE if broken. That's our current theory as to why it happens
