### ISSUE TITLE
how do I do GUI 

### ISSUE THREAD

**Issue by upseguest** [gus33000/UUPMediaCreator#163]
how do I do the GUI one because I tried the cmd one and it had an error while downloading UUPs

**Comment by gus33000** [comment]
There's no gui currently available. Please file a separate issue if you had an error while downloading Unified Update Platform (UUP) update packages though so we can help with it.

**Comment by InternetNinjo** [comment]
> Hi,
> 
>     1. You're replying to a two year old message.
> 
>     2. while there used to be a gui available afterwards it was removed due to overhead with engineering
> 
> 
> This project is built singlehandedly, I simply forgot to update the readme as well.
> 
> I don't understand why you're mad as well, or think there's any wrongdoing such as "clickbait" here.
> 
> I don't see how such a negative reaction is justified, but I will update the readme if this can make you feel better soon?
> 
> Sorry for having spent time making a program on my own with nothing to ask in return? I think here's better ways to express an issue than putting the blame on someone all while accusing actions that aren't even done? This is both all free and done by a single person during their free time afterall... No need to be this rude or toxic.
> 
> As this is a free open source project the old code containing the gui can also be found downloaded and built if you want.
> 
> Im also not entitled to always work on this free project, I'm not a company afterall. So I think not having the time to write code on it and update the readme largely justified not doing it for my defense.

![Image](https://github.com/user-attachments/assets/5fdfdc6e-e547-426d-a137-fc5bac1cd475)
so that's not a GUI? i'm not blind

**Comment by gus33000** [comment]
Hi, as I mentioned previously there used to be one but it was removed. I lack the time to work on this project for more than a year. As the gui was removed long ago there's simply no way to run it. 

As I told you above, I forgot to update the readme to remove that info, and I once again lack the time to work on this project to even find the time to sit at a computer and edit that readme, just because someone like you seems angry and not understanding of that.
