### ISSUE TITLE
Problem with downloading UUP files for windows 10x

### ISSUE THREAD

**Issue by alecs2535** [gus33000/UUPMediaCreator#24]
when downloading UUP files for windows 10x, when you enter this command uupdownload -o dlfolder-s Lite -t amd64 -r External-b Dev -a CB-c fe_release_10x-v 10.0.20279.1002, there is no download, but just an update check and that's it

[12:42:59][Information] UUPDownload 0.3.0.3 - Download from the Microsoft Unified Update Platform
[12:42:59][Information] Copyright (c) Gustave Monce and Contributors
[12:42:59][Information] https://github.com/gus33000/UUPMediaCreator

[12:42:59][Information] This program comes with ABSOLUTELY NO WARRANTY.
[12:42:59][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[12:42:59][Information] Checking for updates...
[12:43:02][Information] Completed.

**Comment by romhacks** [comment]
I have the same issue, running on Windows 10 Pro build 21359. It doesn't seem to attempt to download anything.

**Comment by arnaldocarpi** [comment]
I also have the same problem. but when I try to download other build, I can usually.

**Comment by Tekkie-Boy** [comment]
The problem is that the data does not seem to be available on the servers anymore.

So I don't see it as a bug in the program because it does what it is supposed to do. 

And if a build specified in the parameter can no longer be found on the server, it cannot download it either.

**Comment by gus33000** [comment]
@Tekkie-Boy is correct, the update has been pulled. You likely can get it from various mirrors online still.

**Comment by Fabri247Gato10X** [comment]
I need a link for downloading UUP of Windows 10X, too. ¿Do you can give us an alternative link to Windows 10X UUP files?

**Comment by thebookisclosed** [comment]
This toolset's purpose is to download what's currently hosted on Windows Update. (and potentially convert to an ISO if you're downloading a traditional product like Desktop Client or Server)
Windows 10X is a canceled & practically dead operating system, build 20279 was never officially released -- people just happened to notice it was being served by WU for a short period of time.
There's bound to be countless reuploads of the files over the 2.5+ years since this build's publish date. Grabbing files deliberately unpublished by Microsoft is outside the scope of this issue tracker.
