### ISSUE TITLE
0.3.0.3 Problem in Downloading the UUP.

### ISSUE THREAD

**Issue by Burnuts** [gus33000/UUPMediaCreator#27]
I entered the command on a cmd file.

File:
@echo off
cd /d C:\Users\Admin\10X\win-x64
UUPDownload.exe -s Lite -v 10.0.20250 -t amd64 -b Dev -r External -c fe_release_10x

[16:56:48][Information] UUPDownload 0.3.0.3 - Download from the Microsoft Unified Update Platform
[16:56:48][Information] Copyright (c) Gustave Monce and Contributors
[16:56:48][Information] https://github.com/gus33000/UUPMediaCreator

[16:56:48][Information] This program comes with ABSOLUTELY NO WARRANTY.
[16:56:48][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[16:56:48][Information] Checking for updates...
[16:56:50][Information] Completed.

But it dosent download the UUP files.

**Comment by Tekkie-Boy** [comment]
Hello

as was already written there:
https://github.com/gus33000/UUPMediaCreator/issues/24#issuecomment-821784326

Microsoft removed the files for Win10x from the servers.

Friendly greetings

**Comment by Burnuts** [comment]
Let my try Windows 10 Team

**Comment by Burnuts** [comment]
Even for Windows 10 Team (PPIPro) is not working.

**Comment by Burnuts** [comment]
Downloading the UUP for Windows 10 Team (PPIPro) dosent work.

**Comment by Dynakarp** [comment]
I can confirm, it isn't working for me either

**Comment by Tekkie-Boy** [comment]
@Dynakarp 
You're right.
With version 0.3.0.3 no more builds can be downloaded.
Regarding the Win10x, nothing changes.
We have to wait for a new release.

**Comment by Fabri247Gato10X** [comment]
I'm sorry to tell you that Windows 10X is dead, it's in system heaven, in a better place. Microsoft never intentionally released Windows 10X build 20279, just some users noticed that Windows Update offered Windows 10X build 20279 for a short period of time... but all is not lost, because in the Internet Archive I found 2 Windows UUPs 10 more times! This could help. But not in the same way as before, we will have to continue investigating for now.
